Feature/edit interpretations [DHIS2-3430]
dhis2/dashboard-app pull request #191
Opened 2018-06-05 12:17 UTC by joakimia

This feature enables editing of interpretations, and interpretation comments.
Two more actions are introduced to the store:
- tEditInterpretation
- tEditInterpretationComment

Two more props are added for the <InputField /> used for generating interpretations or comments:
- editing (boolean)
- commentId (Either the interpretation id, or the comment id of the interpretation comment.

Two more API functions are added, before dispatching the action:
- updateInterpretation
- updateInterpretationComment

Editing intepretations works fine, while editing interpretationComments updates data to the API incorrectly (The functions calls JSON.stringify on a text string).

Currently, d2.Api.getApi()**.update()**  within updateInterpretationComment updates the endpoint with additional quotations through JSON.stringify. This means that the payload will consist of quotations which the Regex in d2 API filters incorrectly.

Initially i tried to add helper functions to filter the string, however this is not the best solution.
I spoke with Birk regarding changing the d2 API call, but this will require a breaking API change as we thought the best change would be to add the option parameter for consistency.
(adding if statement to check if input is a string: https://github.com/dhis2/d2/tree/feature/validate-type-update-function). 

Postman updates the endpoint correctly when specified that the payload data is content-type: text-plain. But .update() does not have options available as parameters.

2018-06-06 09:53 UTC, joakimia commented
PR for performing the PUT request with the text/plain option: https://github.com/dhis2/d2/pull/165

I've also added an if statement to verify that the edit contains character, as the PUT request will otherwise prompt an error when the body of the payload is empty.

It also forces the user to delete the edit instead of leaving an empty field (should the attempt to delete the whole text and post the update).

2018-06-08 08:59 UTC, edoardo requested changes
Remove the `new: Joakim` comments 😉 

Also, I think @jenniferarnesen should have a look at this as she worked with the original interpretations component.

2018-06-08 08:59 UTC, edoardo commented on src/Item/PluginItem/Interpretations/Interpretation.js
> +                postText={'Post'}
Remember i18n

2018-06-08 08:59 UTC, edoardo commented on package.json
> +    "moment": "^2.22.1",
is this needed?

2018-06-08 08:59 UTC, edoardo commented on src/Item/PluginItem/Interpretations/Interpretation.js
>              this.props.userIsSuperuser;
Are the conditions the same for both edit and delete?

2018-06-08 08:59 UTC, edoardo commented on src/api/interpretations.js
> +        .then(d2 => d2.Api.getApi().patch(url, { text: data.text }))
I guess with the fix in d2 this should go back to update?

2018-06-08 10:25 UTC, joakimia commented on src/Item/PluginItem/Interpretations/Interpretation.js
> +                postText={'Post'}
Went through the files and added i18n.t 
Asked @jenniferarnesen to take a look as well

2018-06-08 10:25 UTC, joakimia commented on package.json
> +    "moment": "^2.22.1",
Removed this dependency, it is not needed.

2018-06-08 10:25 UTC, joakimia commented on src/Item/PluginItem/Interpretations/Interpretation.js
>              this.props.userIsSuperuser;
I will double check with Scott and @jenniferarnesen , Maybe the owner should have the possibility of both editing and deleting, and super user should only be able to delete.

I'll separate it for now 👍

2018-06-08 10:25 UTC, joakimia commented on src/api/interpretations.js
> +        .then(d2 => d2.Api.getApi().patch(url, { text: data.text }))
Yes i agree, changed it back to .update(),

2018-06-12 07:43 UTC, jenniferarnesen commented on src/Item/PluginItem/Interpretations/Interpretation.js
> +            <p style={style.text}>{i18n.t(item.text)}</p>
@joakimia item.text is the actual comment, so there is no translation for it. So remove the i18n.t part.

2018-06-12 12:20 UTC, jenniferarnesen commented on src/Item/PluginItem/Interpretations/Interpretation.js
>      showCommentField = () => {
The use of this has changed, so it would be good to rename it accordingly (e.g., toggleCommentField)

2018-06-15 09:07 UTC, jenniferarnesen approved these changes

2018-06-15 10:18 UTC, merged