fix: disable LL items if the plugin version does not support installationStatus message
dhis2/dashboard-app pull request #2293
Opened 2023-05-02 13:55 UTC by jenniferarnesen

This is a workaround until a more robust system of plugin version management has been decided on. Without this fix, only the first LL item will load. The rest get an infinite spinner.

With this check:

![image (3)](https://user-images.githubusercontent.com/6113918/235687997-538e04c1-66be-465f-a5a9-f013f67d9825.png)

Without the check:

![image (2)](https://user-images.githubusercontent.com/6113918/235688001-353412f5-5285-47c8-a7a1-c4a1847fb4dd.png)

2023-05-02 14:40 UTC, KaiVandivier requested changes
I think the `isCompatible` logic needs a tweak and some more test conditions, but the rest looks good 👍

2023-05-02 14:40 UTC, KaiVandivier commented on src/modules/isLLVersionCompatible.js
> +        minLLVersion[2] <= versionArray[2]
It looks like v101.0.0 would return `false` here, so this logic needs a little adjustment -- here's a thought:

```js
const [minMajor, minMinor, minPatch] = minLLVersion
const [major, minor, patch ] = versionArray

isCompatible =
    major > minMajor ||
    major === minMajor && minor > minMinor ||
    major === minMajor && minor === minMinor && patch >= minPatch
```

2023-05-02 14:55 UTC, jenniferarnesen commented on src/modules/isLLVersionCompatible.js
> +        minLLVersion[2] <= versionArray[2]
Good catch. Fixed

2023-05-03 08:14 UTC, KaiVandivier approved these changes
Nice! Looks good to me 🙂

2023-05-05 08:22 UTC, merged