feat: slideshow using css and a single fullscreen element
dhis2/dashboard-app pull request #3081
Opened 2024-09-06 09:52 UTC by jenniferarnesen

Implements [DHIS2-XXXX](https://dhis2.atlassian.net/browse/DHIS2-XXXX)

**Requires https://github.com/dhis2/analytics/pull/XXX**

---

### Key features

1. _feature_

---

### Description

_text_

---

### TODO

-   [ ] _task_

---

### Known issues

-   [ ] _issue_

---

### Screenshots

_supporting text_

2024-12-04 10:02 UTC, HendrikThePendric requested changes
These changes are looking great 😍 . I've left a few comments in the code, but nothing critical. I also tested the functionality briefly and did encounter an issue there. When navigating from one item to the next the black area at the bottom of the page seems to briefly expand. Is there anything that can be done about that.

Here's a screen recording:
https://github.com/user-attachments/assets/59bcb161-dde7-4ee2-96dd-146d77cb9c4d

Some additional info:
I'm on MacOS, using a MacBook Pro with M1 Max and showing the slideshow on an external 4K 32" monitor. My browser is Chrome Version 131.0.6778.109 (Official Build) (arm64).

**UPDATE**
I've also tested my on my laptop monitor and the issue cannot be reproduced there. I've also tried on that monitor with CPU throttling enabled, and still wasn't able to replicate the issue.... So it does not appear to be a performance related issue.....

2024-12-04 10:02 UTC, HendrikThePendric commented on cypress/e2e/slideshow.feature
> +        Then the normal view is shown
Without having seen the actual implementation yet, I wonder if perhaps it would add value to add a test scenario for opening the last item and navigating backwards?

2024-12-04 10:02 UTC, HendrikThePendric commented on src/pages/view/styles/ItemGrid.module.css
> +/* stylelint-enable csstools/use-logical */
Luckily I don't think this could cause any issue at all, since the item covers pretty much the entire screen 🤣

2024-12-04 10:02 UTC, HendrikThePendric commented on src/pages/view/useSlideshow.js
> +    }, [displayItems])
Instead of using `useEffect`, I would recommend using `useMemo` here. 
```js
const sortedItems = useMemo(() => sortBy(displayItems, ['y', 'x']).filter((i) =>
    itemTypeSupportsFullscreen(i.type)
), [displayItems])
```

2024-12-04 10:02 UTC, HendrikThePendric commented on src/pages/view/useSlideshow.js
> +    const sortedItems = useRef([])
This const should be replaces by the memoized const.

2024-12-04 10:05 UTC, jenniferarnesen commented on cypress/e2e/slideshow.feature
> +        Then the normal view is shown
Ill add a test for that

2024-12-04 10:13 UTC, jenniferarnesen commented
> These changes are looking great 😍 . I've left a few comments in the code, but nothing critical. I also tested the functionality briefly and did encounter an issue there. When navigating from one item to the next the black area at the bottom of the page seems to briefly expand. Is there anything that can be done about that.

Could you share a video? I don't see it.

2024-12-04 12:13 UTC, HendrikThePendric approved these changes
After fixing the large-monitor-issue and changing to `useMemo`, this PR looks great. Approved 🎉

2024-12-17 12:27 UTC, jenniferarnesen commented on cypress/e2e/slideshow.feature
> +        Then the normal view is shown
Done

2024-12-20 13:52 UTC, janhenrikoverland approved these changes

2024-12-20 15:19 UTC, merged