chore: replace old mui itemlist selector with ui-core components
dhis2/dashboard-app pull request #315
Opened 2019-05-13 12:06 UTC by jenniferarnesen

Also includes some styling changes requested by Joe

2019-05-28 08:59 UTC, cooper-joe commented
Feedback/requested changes:
- 'Show more' sometimes shows nothing more. For example 'Apps' shows just 'Social Media Video' as the only item, but there is still a 'show more' control. Clicking it does nothing except change control text to 'show fewer'. This control should be hidden if there are =<5.
- add an active (click) state to the items, [in my codepen](https://codepen.io/j_cpr/live/73918a10a96df4de0acaeec4e023edcf) I added `background-color:grey400;`

This looks and works great, thanks!

2019-05-28 09:00 UTC, cooper-joe requested changes
Feedback/requested changes:

- 'Show more' sometimes shows nothing more. For example 'Apps' shows just 'Social Media Video' as the only item, but there is still a 'show more' control. Clicking it does nothing except change control text to 'show fewer'. This control should be hidden if there are =<5.
- add an active (click) state to the items, in [the codepen](https://codepen.io/j_cpr/live/73918a10a96df4de0acaeec4e023edcf) I added `background-color:grey400;`

This looks and works great, thanks!

2019-05-28 13:38 UTC, edoardo approved these changes
LGTM

2019-05-28 13:38 UTC, edoardo commented on src/components/ItemSelector/ItemSelector.js
> +    getCatetorizedMenuGroups = items =>
Typo.

2019-05-29 07:37 UTC, cooper-joe approved these changes
approved, the issues I raised will be handled elsewhere:
- show more/show less: backend change requested, so updates will be handled in another pull request
- ui-core menus to be updated with an active state

2019-05-29 08:41 UTC, merged