chore: use colors from @dhis2/ui-core
dhis2/dashboard-app pull request #329
Opened 2019-07-03 10:52 UTC by edoardo

Removed the local colors module.

2019-07-03 10:54 UTC, edoardo commented
There are a couple more hardcoded colors in App.css.

2019-07-29 09:24 UTC, jenniferarnesen commented
The text color for the spacer item looks a little too faded. Other than that, looks good.

2019-07-29 09:37 UTC, cooper-joe requested changes
Just a single change, other than that looks good.

2019-07-29 09:37 UTC, cooper-joe commented on src/components/Item/SpacerItem/Item.js
> +    color: colors.grey400,
Use grey600 instead of grey400 here

2019-07-29 09:40 UTC, jenniferarnesen approved these changes

2019-07-29 09:47 UTC, jenniferarnesen approved these changes

2019-07-29 09:48 UTC, cooper-joe approved these changes

2019-07-29 12:51 UTC, merged