fix: upgrade packages + convert to function components with hooks
dhis2/dashboard-app pull request #348
Opened 2019-10-09 13:32 UTC by janhenrikoverland

**DO NOT MERGE YET**

- Upgrade packages
- Convert class components to function components and replace old lifecycle hooks with useState and useEffect (deprecation warnings in the console)

2019-10-16 10:19 UTC, edoardo approved these changes
Looks good, but i was expecting to see `package.json` modified too.

2019-10-16 13:35 UTC, amcgee requested changes
Looks way cleaner!  Left a few comments - we might want to use `useCallback` instead of regenerating callback functions on each render.

2019-10-16 13:35 UTC, amcgee commented on src/components/ControlBar/Filter.js
> +    }, [props.name]);
This actually has a slightly different behavior than the previous version - before, the "state" would always start as DEFAULT_STATE_DASHBOARDS_FILTER_NAME even if `props.name` was set; after, it will render once as `DEFAULT_STATE_DASHBOARDS_FILTER_NAME` and then immediately re-render as `props.name`

Since `setValue` is only ever called in `useEffect`, I actually don't think the hooks are necessary - it could just be `const value = props.name || DEFAULT_STATE_DASHBOARDS_FILTER_NAME`

**NOTE** This would actually cause the "escape" behavior to reset to the default, rather than to blank, is that something we want to avoid?

2019-10-16 13:35 UTC, amcgee commented on src/components/ControlBar/Filter.js
> +    const handleKeyUp = event => {
To make sure this is a stable function reference (better for pure components) this could be `useCallback(event => {...}, [props])`, otherwise it will recreate the function on every render (unlike the previous version)

2019-10-16 13:35 UTC, amcgee commented on src/components/ControlBar/__tests__/Filter.spec.js
> -    describe('when updated name property is provided', () => {
Why was this test removed?

2019-10-16 13:35 UTC, amcgee commented on src/components/ItemGrid/ItemGrid.js
> +    }, [props.edit]);
I **think** (worth confirming) that using sub-properties (`props.edit`) in the dependency array won't work as expected, since the `props` variable is the one bound to the function initialization.  So I think it would need to be `[props]` as dependency.

2019-10-18 20:30 UTC, janhenrikoverland commented on src/components/ControlBar/Filter.js
> +    const handleKeyUp = event => {
Agreed (now that I know useCallback :-)

2019-10-18 20:50 UTC, janhenrikoverland commented on src/components/ControlBar/Filter.js
> +    }, [props.name]);
You are right, removing the hooks is actually better.

Regarding "escape", the redux reducer will return default when the component calls props.onChangeName() without arguments.

2020-05-15 22:46 UTC, amcgee commented
Oof, this got stale but it's still pretty great.  Can we take this `off-hold`?

2020-10-14 05:27 UTC, jenniferarnesen commented
Superceded by this PR: https://github.com/dhis2/dashboards-app/pull/1177

2020-10-14 05:27 UTC, closed without merging