fix: edit mode performance improvements
dhis2/dashboard-app pull request #617
Opened 2020-03-09 19:37 UTC by janhenrikoverland

- Uses memoization in ItemGrid.js on both the items array and more importantly the actual items in the items array to avoid rerendering the VisualizationItem components unnecessarily
- Changes the RECEIVED_DASHBOARD_LAYOUT to not always produce new dashboard items (important). Also simply returns current state when no items changed.
- Using lodash memoize, which remembers all inputs, instead of memoize-one which only remembers the last value

2020-03-09 22:59 UTC, jenniferarnesen commented on src/components/Item/VisualizationItem/Item.js
> +        this.memoizedApplyFilters = memoize(this.applyFilters);
Using lodash memoize breaks the filtering (see the documentation - only the first value of the memoized function is used as the cache key).  So I think we should stick with memoizeOne in this file.

2020-03-09 23:09 UTC, jenniferarnesen commented on src/components/ItemGrid/ItemGrid.js
> +        this.getMemoizedItemComponents = memoize(this.getItemComponents);
I tried using each of these on their own. The only one that actually decreased number of renders was getMemoizedItem (line 56). So I think we can safely remove the other 3 and have the same result.

2020-03-09 23:25 UTC, jenniferarnesen requested changes
Edit mode is so much faster! See comments for requested changes.

2020-03-10 10:33 UTC, janhenrikoverland commented
Typing in a textbox is fast again as it doesn't affect other items anymore. Same thing for resizing when it doesn't touch other (or only a few) items. However resizing one of the top items vertically which pushes all the other items is still a bit slow (was way faster in 2.33), need to investigate further on this.

2020-03-10 10:38 UTC, merged